const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      desc: 'high qualtiy shirt',
    },
    {
      name: 'Addidas Slim shirt',
      slug: 'addidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 300,
      countInStock: 40,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 15,
      desc: 'high qualtiy shirt',
    },
    {
      name: 'Addidas Slim pants',
      slug: 'addidas-slim-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 30,
      countInStock: 10,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 15,
      desc: 'high qualtiy pants',
    },
    {
      name: 'Nike Slim pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 20,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      desc: 'high qualtiy pants',
    },
  ],
};

export default data;
